### ISSUE TITLE
can not runing in node 8

### ISSUE THREAD

**Issue by xqin** [andreasonny83/lighthouse-ci#61]
`lighthouse-ci`  engines `>=6`, but `lighthouse` need engines `>=10.13`.

so when i use node v8.9.4, i can success install lighthouse-ci, but i can't run it.

![image](https://user-images.githubusercontent.com/1265888/74826555-bfdd7800-5346-11ea-812a-075dbe62a52a.png)

```
jenkins@c76f8d0afa9d:~/a$ ./node_modules/.bin/lighthouse-ci --help
/home/jenkins/a/node_modules/lighthouse/lighthouse-core/lib/url-shim.js:36
class URLShim extends URL {
                      ^

ReferenceError: URL is not defined
    at Object.<anonymous> (/home/jenkins/a/node_modules/lighthouse/lighthouse-core/lib/url-shim.js:36:23)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/jenkins/a/node_modules/lighthouse/lighthouse-core/lib/network-request.js:14:13)
    at Module._compile (module.js:643:30)
```

https://github.com/andreasonny83/lighthouse-ci/blob/v1.10.0/package.json#L46-L48

![image](https://user-images.githubusercontent.com/1265888/74826227-329a2380-5346-11ea-8cd2-b86e93a69291.png)

---

https://github.com/GoogleChrome/lighthouse/blob/master/package.json#L10-L12

![image](https://user-images.githubusercontent.com/1265888/74826347-65dcb280-5346-11ea-99bd-de0b00aa43c6.png)

https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/lib/url-shim.js#L35-L36

![image](https://user-images.githubusercontent.com/1265888/74826423-8a388f00-5346-11ea-8528-5de8062a1a26.png)

**Comment by andreasonny83** [comment]
Thanks for reporting. I'll upgrade the minimum node version required to 10.13 in the next version
