### ISSUE TITLE
Error: Cannot find module 'lighthouse/report/report-generator'

### ISSUE THREAD

**Issue by tomMolin** [andreasonny83/lighthouse-ci#88]
Just after installing lh-ci under node v16.2.0 `npm install -g lighthouse-ci@1`, I got this error:

```
lighthouse-ci --help  
node:internal/modules/cjs/loader:944
  throw err;
  ^

Error: Cannot find module 'lighthouse/report/report-generator'
Require stack:
- /Users/tmolin/.nvm/versions/node/v16.2.0/lib/node_modules/lighthouse-ci/lib/lighthouse-reporter.js
- /Users/tmolin/.nvm/versions/node/v16.2.0/lib/node_modules/lighthouse-ci/bin/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
    at Function.Module._load (node:internal/modules/cjs/loader:774:27)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/tmolin/.nvm/versions/node/v16.2.0/lib/node_modules/lighthouse-ci/lib/lighthouse-reporter.js:13:25)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/tmolin/.nvm/versions/node/v16.2.0/lib/node_modules/lighthouse-ci/lib/lighthouse-reporter.js',
    '/Users/tmolin/.nvm/versions/node/v16.2.0/lib/node_modules/lighthouse-ci/bin/cli.js'
  ]
}
```

Downgrading to v1.12.0 is fine, but is there a workaround / fix 🤷

**Comment by javierlopezdesign** [comment]
I've just updated my version since December w2020 and I got the same error.

If you edit this file in your end:
Users/tmolin/.nvm/versions/node/v16.2.0/lib/node_modules/lighthouse-ci/lib/lighthouse-reporter.js
And comment the line number 13, lighthouse will work, but no reports will be saved as it doesn't get the module. It's the far that I could go at 3 am hehe.

**Comment by tomMolin** [comment]
Thanks for the tip, but i use it on an automated CI process. I could do a `sed` replacement to bypass the report but if there is another solution 😄

**Comment by dsuttler** [comment]
The path is incorrect in the file. Alter the path name and it works fine, reports and all.

Currently getting an error: 

_eventEmitter = new EventEmitter(); /** @type {CrdpEventEmitter} */ 
                ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/lib/node_modules/lighthouse-ci/node_modules/lighthouse/lighthouse-core/runner.js:9:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

Any ideas?

**Comment by dsuttler** [comment]
@fairbairn check your Node version. I just updated from 10.x.x to 14.18.0 and the error went away. Now the error that @tomMolin posted comes up. I'll fix it again and post the fix.
